
export const leftNavData = [
  {
    id: 'home',
    path: '/home',
    name: '首页',
    iconType: 'antd',
    icon: 'home',
    query: {},
  },
  {
    id: 'userManage',
    path: '/userManage',
    name: '用户管理',
    iconType: 'antd',
    icon: 'team',
    query: {},
    children: [
      {
        id: 'userManageEcharts',
        path: '/userManage/echarts',
        name: '统计分析',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList',
        path: '/userManage/list',
        name: '商家用户列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageAdmin',
        path: '/userManage/admin',
        name: '系统用户列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageMember',
        path: '/userManage/member',
        name: '会员列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageGrade',
        path: '/userManage/grade',
        name: '会员等级',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'authManage',
    path: '/authManage',
    name: '权限管理',
    iconType: 'antd',
    icon: 'team',
    query: {},
    children: [
      {
        id: 'authManageRole',
        path: '/authManage/role',
        name: '角色管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'authManageList',
        path: '/authManage/list',
        name: '权限列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'authManageModule',
        path: '/authManage/module',
        name: '权限模块',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'storeManage',
    path: '/storeManage',
    name: '店铺管理',
    iconType: 'fa',
    icon: 'fa-cube',
    query: {},
    children: [
      {
        id: 'storeEcharts',
        path: '/storeManage/echarts',
        name: '统计分析',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'storeList',
        path: '/storeManage/list',
        name: '店铺列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'storeRecommend',
        path: '/storeManage/recommend',
        name: '店铺推荐',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'goodsManage',
    path: '/goodsManage',
    name: '商品管理',
    iconType: 'fa',
    icon: 'fa-cube',
    query: {},
    children: [
      {
        id: 'goodsEcharts',
        path: '/goodsManage/echarts',
        name: '统计分析',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'goodsList',
        path: '/goodsManage/list',
        name: '商品列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'goodsRecommend',
        path: '/goodsManage/recommend',
        name: '商品推荐',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'historyRecord',
    path: '/historyRecord',
    name: '历史记录',
    iconType: 'fa',
    icon: 'fa-cube',
    query: {},
    children: [
      {
        id: 'historyRecordDeleteUserList',
        path: '/historyRecord/deleteUser',
        name: '删除用户历史',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'historyRecordDeleteAdminUserList',
        path: '/historyRecord/deleteAdminUser',
        name: '删除系统用户历史',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'orderManage',
    path: '/orderManage',
    name: '订单管理',
    iconType: 'fa',
    icon: 'fa-cube',
    query: {},
    children: [
      {
        id: 'orderManageList',
        path: '/orderManage/list',
        name: '订单列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'orderManage',
        path: '/orderManage/proList',
        name: '问题订单',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'message',
    path: '/message',
    name: '消息中心',
    iconType: 'fa',
    icon: 'fa-envelope-o',
    query: {},
  },
  {
    id: 'systemSet',
    path: '/systemSet',
    name: '系统设置',
    iconType: 'fa',
    icon: 'fa-cog',
    query: {},
  }
];
